using DynamicProxy;
using Umi.Proxy.Dynamic.Aspect;

namespace Umi.Proxy.Dynamic.Dynamic;

public abstract class AutoGeneratedBase : IEventRaise
{
    private readonly IInvoker _invoker;
    private readonly IEnumerable<IInterceptor> _interceptors;
    private readonly IEventProcessor _eventProcessor;

    // ReSharper disable once ConvertToPrimaryConstructor
    protected AutoGeneratedBase(
        IInvoker invoker,
        IEventProcessor eventProcessor,
        IEnumerable<IInterceptor> interceptors)
    {
        _invoker = invoker;
        _eventProcessor = eventProcessor;
        _interceptors = interceptors;
        RaiseUuid = Guid.NewGuid();
    }

    protected void EventSubscribe(string eventName) => _eventProcessor.Subscribe(this, eventName);

    protected void EventUnsubscribe(string eventName) => _eventProcessor.Unsubscribe(this, eventName);

    protected void Process(IMethodInvocation input)
    {
        // 先 invoke 拦截器
        if (_interceptors.Any(interceptor => !interceptor.BeforeInvoke(input)))
        {
            return;
        }

        // 调用实际实现
        try
        {
            _invoker.Process(input);
        }
        catch (Exception e)
        {
            foreach (var interceptor in _interceptors)
            {
                interceptor.ExceptionInvoke(input, e);
            }

            throw;
        }

        // 调用后置拦截器
        foreach (var interceptor in _interceptors)
        {
            interceptor.AfterInvoke(input);
        }
    }

    protected static void ProcessStatic(IMethodInvocation input)
    {
    }

    public Guid RaiseUuid { get; }

    public abstract void RaiseEvent(string @event, EventArgs args);
}