namespace Umi.Proxy.Dynamic.Dynamic;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class AutoGeneratedGuidAttribute : Attribute
{
    private readonly Guid _uuid;

    public Guid Uuid => _uuid;

    public AutoGeneratedGuidAttribute(string uuid)
    {
        if (!Guid.TryParse(uuid, out _uuid))
        {
            _uuid = Guid.NewGuid();
        }
    }
}