using DynamicProxy;
using Umi.Proxy.Dynamic.Aspect;

namespace Umi.Proxy.Dynamic.Dynamic;

public abstract class AutoGeneratedBase(IInvoker invoker, IEnumerable<IInterceptor> interceptors)
{
    protected void Process(IMethodInvocation input)
    {
        // 先 invoke 拦截器
        if (interceptors.Any(interceptor => !interceptor.BeforeInvoke(input)))
        {
            return;
        }

        // 调用实际实现
        try
        {
            invoker.Process(input);
        }
        catch (Exception e)
        {
            foreach (var interceptor in interceptors)
            {
                interceptor.ExceptionInvoke(input, e);
            }

            throw;
        }

        // 调用后置拦截器
        foreach (var interceptor in interceptors)
        {
            interceptor.AfterInvoke(input);
        }
    }

    protected static void ProcessStatic(IMethodInvocation input)
    {
    }
}